#ifndef COMMONDEFINE_HPP_
#define COMMONDEFINE_HPP_

#define INDEX_COUNT 1024*1024
#define REQUEST_PORT 1991
#define MANAGE_PORT 1993
#define REQUEST_HANDLER_NUM 1
#define RESPONSER_NUM 1
#define TRY_COUNT 1000
#define SLEEP_TIME 10

#endif
